# GitHub Action to build & test the CopilotMvcMusicStore solution
name: Build & Test Solution
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore ./src/CopilotMvcMusicStore.sln
      - name: Build solution
        run: dotnet build ./src/CopilotMvcMusicStore.Web/CopilotMvcMusicStore.Web.csproj --configuration Release
      - name: Run tests
        run: dotnet test ./src/CopilotMvcMusicStore.Test/CopilotMvcMusicStore.Test.csproj --logger "trx;LogFileName=test_results.trx"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
                ./src/CopilotMvcMusicStore.Test/TestResults/test_results.trx
      